# Generated by Django 2.2.2 on 2019-06-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=30)),
                ('tarjeta', models.CharField(max_length=20)),
                ('banco', models.CharField(default='Banco estado', max_length=20)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DuenoE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(default='Holas123', max_length=100)),
                ('cuentaB', models.CharField(default='Credito', max_length=20)),
                ('edificio', models.CharField(default='1 32 A', max_length=20)),
                ('piso', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutUsuario', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
