# Generated by Django 2.1.2 on 2019-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dueñoE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=30)),
                ('tarjeta', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
    ]
