# Generated by Django 2.1.2 on 2019-06-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dueñoE',
            new_name='duenoE',
        ),
    ]
