# Generated by Django 2.2.2 on 2019-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patenteVe', models.CharField(max_length=10)),
                ('codEstacionamieno', models.IntegerField()),
                ('HoraIni', models.IntegerField()),
                ('HoraFin', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstacionamientoActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutDueno', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('piso', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('precioHora', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='duenoe',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
