# Generated by Django 2.1.2 on 2019-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0002_auto_20190619_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutUsuario', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='duenoe',
            name='cuentaB',
            field=models.CharField(default='Credito', max_length=20),
        ),
        migrations.AddField(
            model_name='duenoe',
            name='direccion',
            field=models.CharField(default='Holas123', max_length=100),
        ),
        migrations.AddField(
            model_name='duenoe',
            name='edificio',
            field=models.CharField(default='1 32 A', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='banco',
            field=models.CharField(default='Banco estado', max_length=20),
        ),
    ]
